import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  modalCoverBottom: {
    height: '50%',
    width: '100%',
    marginTop: 'auto',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalTouchableLayout: {
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  modalCoverMiddle: {
    height: '30%',
    width: '100%',
    marginTop: 'auto',
    marginBottom: 'auto',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textMiddleHeader: {marginBottom: 30, fontSize: 16, fontWeight: 'bold'},
  modalContentMiddle: {
    width: '80%',
    backgroundColor: '#FFF',
    shadowColor: '#000',
    // elevation: 5,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    height: 150,
    borderRadius: 10,
  },
  modalContentBottom: {
    width: '90%',
    borderRadius: 10,
    backgroundColor: '#FFFF',
    height: 200,
    justifyContent: 'center',
    alignContent: 'center',
    shadowColor: '#393939',
    elevation: 5,
  },
  buttonMiddleWrapper: {
    width: '70%',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  buttonWrapper: {flexDirection: 'row', justifyContent: 'center'},
  buttonPrimary: {
    backgroundColor: '#d7dadd',
    width: '80%',
    marginHorizontal: 'auto',
    padding: 10,
    borderRadius: 7,
    marginVertical: 7,
  },
  buttonPrimarySm: {
    backgroundColor: '#d7dadd',
    width: 100,
    marginHorizontal: 'auto',
    padding: 10,
    borderRadius: 7,
    marginVertical: 7,
  },
  textBtnPrimary: {
    textAlign: 'center',
    color: '#393939',
    fontSize: 16,
    fontWeight: 'bold',
  },
  buttonSecondary: {
    backgroundColor: '#7a8793',
    width: '80%',
    marginHorizontal: 'auto',
    padding: 10,
    borderRadius: 7,
    marginVertical: 7,
  },
  buttonSecondarySm: {
    backgroundColor: '#7a8793',
    width: 100,
    marginHorizontal: 'auto',
    padding: 10,
    borderRadius: 7,
    marginVertical: 7,
  },
  btnYellowSm: {
    backgroundColor: '#FFCD61',
    width: 100,
    marginHorizontal: 'auto',
    padding: 10,
    borderRadius: 7,
    marginVertical: 7,
  },
  textBtnYellow: {
    textAlign: 'center',
    fontSize: 16,
    fontWeight: 'bold',
  },
  textBtnSecondary: {textAlign: 'center', color: '#FFFF', fontSize: 16},
});
export default styles;
